/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LED_1.h"
#include "LED_1_aliases.h"
#include "RED.h"
#include "RED_aliases.h"
#include "WHITE.h"
#include "WHITE_aliases.h"
#include "PWM_W.h"
#include "Clock_1.h"
#include "LED_2.h"
#include "LED_2_aliases.h"
#include "LED_3.h"
#include "LED_3_aliases.h"
#include "LED_4.h"
#include "LED_4_aliases.h"
#include "LED_6.h"
#include "LED_6_aliases.h"
#include "LED_7.h"
#include "LED_7_aliases.h"
#include "LED_8.h"
#include "LED_8_aliases.h"
#include "LED_9.h"
#include "LED_9_aliases.h"
#include "ISR_W.h"
#include "LED_5.h"
#include "LED_5_aliases.h"
#include "ISR_R.h"
#include "PWM_R.h"
#include "ISR_W0.h"
#include "ISR_R0.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Button.h"
#include "Button_CSHL.h"
#include "Button_TunerHelper.h"
#include "Button_SMS.h"
#include "Button_PVT.h"
#include "Button_IP.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_SCB_IRQ.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "Button_SampleClk.h"
#include "Button_Sns_aliases.h"
#include "Button_SenseClk.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

